name: Continuous Integration

on:
  push:
    branches:
      - main


jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 20

      - name: Install node modules
        run: |
          npm install
          
      - name: ESLint check
        run: |
          npm run eslint:test
